server:
  port: 7002
  error:
    include-message: always

spring:
  application:
    name: recommendation
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
  cloud:
    stream:
      defaultBinder: rabbit
      default:
        contentType: application/json
      bindings:
        input:
          destination: recommendations
          group: recommendationsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
server:
  port: 8080

spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb

---
spring:
  profiles: streaming_partitioned
  cloud:
    stream:
      bindings:
        input:
          consumer:
            partitioned: true
            instanceCount: 2

---
spring:
  profiles: streaming_instance_0
  cloud:
    stream:
      bindings:
        input:
          consumer:
            instanceIndex: 0
---
spring:
  profiles: streaming_instance_1
  cloud:
    stream:
      bindings:
        input:
          consumer:
            instanceIndex: 1
---
spring:
  profiles: kafka
  cloud:
    stream:
      defaultBinder: kafka

management:
  health:
    rabbit:
      enabled: false

