server:
  port: 7001
  error:
    include-message: always

spring:
  application:
    name: product-service

logging:
  level:
    root: INFO
    com.songko: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080