server:
  port: 7003
  error:
    include-message: always

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/review-db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 1111
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.songko: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/review-db
    username: root
    password: rootpwd
server:
  port: 8080