server:
  port: 7003
  error:
    include-message: always

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/review-db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 1111
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      defaultBinder: rabbit
      default:
        contentType: application/json
      bindings:
        input:
          destination: reviews
          group: reviewsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        # UP, DOWN 결과뿐만 아니라 의존성에 대한 정보가 포함된 상태 점검 세부 정보를 표시
        include: "*"
  endpoint:
    health:
      #  HTTP를 사용해 모든 엔드포인트를 공개
      show-details: always

logging:
  level:
    root: INFO
    com.songko: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
server:
  port: 8080

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql/review-db
    username: root
    password: rootpwd
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka


